// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PgAdvisor.Api.Data;

#nullable disable

namespace PgAdvisor.Api.Data.Migrations
{
    [DbContext(typeof(AdvisorDbContext))]
    [Migration("20260821173658_AddFindingStatusLastSeenIndex")]
    partial class AddFindingStatusLastSeenIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PgAdvisor.Api.Data.Finding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DetectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documentation")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Impact")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemediationSql")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "Status");

                    b.HasIndex("Status", "LastSeenAt");

                    b.HasIndex("ConnectionId", "RuleId", "TargetKey")
                        .IsUnique();

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.FindingHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .HasColumnType("TEXT");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FindingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FindingId", "At");

                    b.ToTable("FindingHistory");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.NotificationConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("generic");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("LastAttemptSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinimumSeverity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("NotificationConfigurations");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.NotificationHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Cycle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("finding");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId", "Subject", "SubjectId", "Event", "Cycle")
                        .IsUnique();

                    b.ToTable("NotificationHistory");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.PostgresConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("CollectionIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastCollectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerVersion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerVersionNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SslMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimescaleVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PostgresConnections");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.QueryPlanSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<long>("MeasuredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sql")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "QueryKey")
                        .IsUnique();

                    b.ToTable("QueryPlanSnapshots");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.RuleHealth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveSlowRuns")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IncidentsSince")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LastDurationMs")
                        .HasColumnType("REAL");

                    b.Property<long?>("LastFailureAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastFailureKind")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFailureMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSuccessAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxDurationMs")
                        .HasColumnType("REAL");

                    b.Property<int>("QuarantineCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuarantineReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("QuarantinedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("QuarantinedUntil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("ConnectionId", "RuleId")
                        .IsUnique();

                    b.ToTable("RuleHealth");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.RuleOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("RuleId", "ConnectionId")
                        .IsUnique();

                    b.ToTable("RuleOverrides");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.Finding", b =>
                {
                    b.HasOne("PgAdvisor.Api.Data.PostgresConnection", "Connection")
                        .WithMany("Findings")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.FindingHistoryEntry", b =>
                {
                    b.HasOne("PgAdvisor.Api.Data.Finding", "Finding")
                        .WithMany("History")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.NotificationConfiguration", b =>
                {
                    b.HasOne("PgAdvisor.Api.Data.PostgresConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.NotificationHistoryEntry", b =>
                {
                    b.HasOne("PgAdvisor.Api.Data.NotificationConfiguration", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.QueryPlanSnapshot", b =>
                {
                    b.HasOne("PgAdvisor.Api.Data.PostgresConnection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.RuleHealth", b =>
                {
                    b.HasOne("PgAdvisor.Api.Data.PostgresConnection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.RuleOverride", b =>
                {
                    b.HasOne("PgAdvisor.Api.Data.PostgresConnection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.Finding", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("PgAdvisor.Api.Data.PostgresConnection", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
